# Generated by Django 5.2.2 on 2025-06-24 21:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0002_remove_project_created_at_remove_project_developer_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='project_url',
            field=models.URLField(blank=True, max_length=255, null=True, verbose_name='Project URL'),
        ),
    ]
