# Generated by Django 5.2.2 on 2025-06-28 04:27

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0004_remove_profile_created_at_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='clientfeedback',
            options={},
        ),
        migrations.AlterModelOptions(
            name='projectupdate',
            options={},
        ),
        migrations.RenameField(
            model_name='clientfeedback',
            old_name='message',
            new_name='content',
        ),
        migrations.RenameField(
            model_name='clientfeedback',
            old_name='response_timestamp',
            new_name='response_date',
        ),
        migrations.RenameField(
            model_name='clientprofile',
            old_name='phone',
            new_name='phone_number',
        ),
        migrations.RenameField(
            model_name='project',
            old_name='full_description',
            new_name='description',
        ),
        migrations.RenameField(
            model_name='projectupdate',
            old_name='description',
            new_name='content',
        ),
        migrations.RemoveField(
            model_name='clientfeedback',
            name='is_resolved',
        ),
        migrations.RemoveField(
            model_name='clientfeedback',
            name='responded_by',
        ),
        migrations.RemoveField(
            model_name='clientfeedback',
            name='timestamp',
        ),
        migrations.RemoveField(
            model_name='clientprofile',
            name='has_viewed_dashboard',
        ),
        migrations.RemoveField(
            model_name='project',
            name='project_url',
        ),
        migrations.RemoveField(
            model_name='projectupdate',
            name='created_by',
        ),
        migrations.RemoveField(
            model_name='projectupdate',
            name='preview_file',
        ),
        migrations.RemoveField(
            model_name='projectupdate',
            name='preview_image',
        ),
        migrations.RemoveField(
            model_name='projectupdate',
            name='preview_url',
        ),
        migrations.RemoveField(
            model_name='projectupdate',
            name='timestamp',
        ),
        migrations.AddField(
            model_name='clientfeedback',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='clientfeedback',
            name='rating',
            field=models.IntegerField(choices=[(1, '1 - Poor'), (2, '2 - Fair'), (3, '3 - Good'), (4, '4 - Very Good'), (5, '5 - Excellent')], default=3),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='clientprofile',
            name='contact_email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='clientprofile',
            name='industry',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='projectupdate',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='projectupdate',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='update_images/'),
        ),
        migrations.AlterField(
            model_name='clientfeedback',
            name='client',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='feedback_given', to=settings.AUTH_USER_MODEL),
        ),
    ]
