# Generated by Django 5.2.2 on 2025-06-28 04:44

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0005_alter_clientfeedback_options_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='clientfeedback',
            name='is_resolved',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='clientfeedback',
            name='responded_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='responses', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='clientprofile',
            name='has_viewed_dashboard',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='projectupdate',
            name='created_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_updates', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='projectupdate',
            name='preview_file',
            field=models.FileField(blank=True, null=True, upload_to='update_files/'),
        ),
        migrations.AddField(
            model_name='projectupdate',
            name='preview_url',
            field=models.URLField(blank=True, null=True),
        ),
    ]
